### ISSUE TITLE
可以适配国产kingbase吗?

### ISSUE THREAD

**Issue by amwu** [sagframe/sagacity-sqltoy#26]
RT

**Comment by chenrenfei** [comment]
第一次听说kingbase，也不知道这个数据库使用情况如何，之前达梦数据库要求支持，支持后发现根本就没有相关用户

**Comment by chenrenfei** [comment]
开始适配

**Comment by chenrenfei** [comment]
开始支持kingbase，但没有想过资料，不知道其分页 和 saveOrUpdate （oracle是merge into） 怎么实现的，或者说kingbase语法是oracle模式还是postgresql模式还是mysql模式

**Comment by chenrenfei** [comment]
4.16.10版本已经完成kingbase的支持
