### ISSUE TITLE
疑问！

### ISSUE THREAD

**Issue by plmokn86** [sagframe/sagacity-sqltoy#28]
开源的代码与在实际项目中用的代码完全一致吗？

**Comment by chenrenfei** [comment]
为什么会有这个疑问？sqltoy是先在项目中用，验证完再发版的。
目前master上跟4.15.0 有点小变化，合并了下一版的一些调整。

**Comment by chenrenfei** [comment]
master跟4.15.0 差异是将一些反调改为了函数式接口模式

**Comment by plmokn86** [comment]
看到网上介绍后，就下来看了一下源代码，发现很多不妥之处，感觉用在主页所罗列的项目中有些小问题。比如：所用的定时刷新缓存方法，不仅存在性能问题，还存在不一致性的问题，目前有很多方法可以避免这些问题。

**Comment by chenrenfei** [comment]
非常感谢回复！
目前默认提供了增量定时更新机制。
这是框架默认提供的，开发者可以根据实际情况进行扩展结合redis做近实时的缓存更新！

因为缓存一般都是缓存相对固定的，而且一般用于名称翻译，绝大多数情况下有一个几秒的时差是可以的。
近实时的缓存更新实现起来是相对复杂的，尤其在分布式场景下，要是按照这个标准作为默认实现开发者就全蒙了，所有标准功能适度简单，如有需要则自行扩展，我们实际项目中就是结合利用canel消费binlog放入kafka，再消费kafka写redis，再通过客户端监听redis来完成近实时更新的，太复杂了！

**Comment by chenrenfei** [comment]
缓存只是用于翻译，名称一般不会经常变化，而key是绝对不会变的，所以只是在显示名称上会有延时，而参与逻辑处理的是key
