### ISSUE TITLE
idea xml 显示报错

### ISSUE THREAD

**Issue by dmyz** [sagframe/sagacity-sqltoy#31]
@chenrenfei  插件要更新啊
![image](https://user-images.githubusercontent.com/15307200/100899552-f0b92300-34fc-11eb-9f56-994da5a07679.png)

**Comment by chenrenfei** [comment]
已经通知sqltoy-tools的开发者，这个工具不是我开发的，也是一个好心的网友开发的

https://github.com/threefish/sqltoy-idea-plugins
