### ISSUE TITLE
SQL不正确的解析

### ISSUE THREAD

**Issue by zhkkjun** [sagframe/sagacity-sqltoy#32]
使用sqltoy-quickstart项目测试
测试方法com.sqltoy.quickstart.dao.StaffInfoDao#findStaff
// 单表查询一般适用于接口内部查询
String sql = "#[staffName like :staffName]#[and createTime>=:beginDate]#[and createTime<=:endDate]";
修改为
String sql = "#[staffName = ']' OR staffName like :staffName]#[and createTime>=:beginDate]#[and createTime<=:endDate]";
运行测试后报错：java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
sqltoy将sql语义中字符串内的“]”做为“#["的配对解析了
猜测其他方法也有类似的问题如 @if(:staffName = ')')等

**Comment by chenrenfei** [comment]
sql查询参数值是动态传入的，遵循这个原则，就不会有这个问题

**Comment by zhkkjun** [comment]
> 1、sql中的参数值应该是动态传入的，遵循这个原则，就不会有这个问题
> 2、就算有一些需求是写死参数值在sql中的，常规也是状态类、枚举类型相关的，怎么可能会包含这些特殊符号？如果有就通过动态传参数来解决！
> 
> 综上在约定大于配置的规则前提下，除非刻意挑战规则否则现实中绝无此场景
> 这个在设计之初就充分思考过这个问题，经历十几年也没有这种情况出现！

比如数据库中的JSON字段形式如空数组的情况：”[]“，这种特殊字符串是存在的，即时业务场景不多，但确实是客观存在的，并不是无故找茬

**Comment by chenrenfei** [comment]
是存在的，但通过动态传参就可以克服了这个问题，sqltoy还提供了@value(:paramName) 等协助处理，就可以化解这种问题
