### ISSUE TITLE
希望quickvo.xml的primary-key主键配置sequence策略时，能支持正则表达式

### ISSUE THREAD

**Issue by WenTao-Love** [sagframe/sagacity-sqltoy#34]
今天终于说服团队使用sqltoy来开发了，哈哈……
想要的效果：
`
<primary-key>
            
           
           
	    <table name="^NETBANK_\w+" strategy="sequence"  sequence="SEQ_\w"/>
	</primary-key>
`

**Comment by chenrenfei** [comment]
这个是好建议

**Comment by WenTao-Love** [comment]
目前我是山寨QuickVOStart的逻辑，打印出来，然后再复制黏贴。

File quickvoxml = FileUtil.file("quickvo.xml");
		String[] args = {quickvoxml.getAbsolutePath()};
		
		//以下是针对主键序列生成xml配置
		Constants.BASE_LOCATE = System.getProperty("user.dir");
		Constants.QUICK_CONFIG_FILE = args[0];
		ConfigModel configModel = XMLConfigLoader.parse();
		TaskController.setConfigModel(configModel);
		for (Iterator iter = configModel.getTasks().iterator(); iter.hasNext();) {
			QuickModel quickModel = (QuickModel) iter.next();
			boolean isConn = DBHelper.getConnection(quickModel.getDataSource());
			if(isConn) {
				String[] includes = null;
//				boolean skipPkConstraint = Constants.getSkipPkConstraint();
				if (quickModel.getIncludeTables() != null) {
					includes = new String[] { "(?i)".concat(quickModel.getIncludeTables()) };
				}
//				int dbType = DBHelper.getDBType();
//				String dialect = DBHelper.getDBDialect();
				// (?i)忽略大小写
				List tables = DBHelper.getTableAndView(includes, quickModel.getExcludeTables() == null ? null
						: new String[] { "(?i)".concat(quickModel.getExcludeTables()) });
				//<table name="NETBANK_BANK_ACCT" strategy="sequence" sequence="SEQ_BANK_ACCT"/>
				for (int i = 0; i < tables.size(); i++) {
					TableMeta tableMeta = (TableMeta) tables.get(i);
					String tableName = tableMeta.getTableName();
					String subTableName = StrUtil.replaceIgnoreCase(tableName, quickModel.getEntitySubstr(), "");
//					System.out.println(tableName);
					String pkStrategy = "<table name=\""+tableName+"\" strategy=\"sequence\" sequence=\"SEQ"+subTableName+"\"/>";
					System.out.println(pkStrategy);
				}
			}
			DBHelper.close();
		}

**Comment by chenrenfei** [comment]
不急，这个我会很快加上，你加入到QQ群里面，我先发一个版本给你

**Comment by chenrenfei** [comment]
TaskController 中第366行，修改一下：
//支持sequence命名以seq_${tableName} 跟表名有规则相关模式
quickColMeta.setSequence(sequence.replaceFirst("(?i)\\$?\\{\\s*tableName\\s*\\}", tableName));

**Comment by chenrenfei** [comment]
到quickvo项目下面去下载4.18.6版本
https://gitee.com/sagacity/sagacity-quickvo
