### ISSUE TITLE
为什么DBHelper.getConnection()方法不是返回数据库连接Connection呢？

### ISSUE THREAD

**Issue by WenTao-Love** [sagframe/sagacity-sqltoy#36]
DBHelper.getConnection(String dbName)，居然是返回布尔值。
我想再次利用他，来进行一些便捷开发。

**Comment by chenrenfei** [comment]
这里就是针对quickvo的写法，里面的工具类不通用，quickvo里面的代码本身没有刻意去优化，定位就是一个生成pojo的工具而已
