### ISSUE TITLE
是否提供AOP接口方式调用SQL?

### ISSUE THREAD

**Issue by imyuyu** [sagframe/sagacity-sqltoy#39]
目前基于sql的id进行入参查询，导致对编码非常不友好，目前使用过程中主要有以下问题：

- 代码中存在大量字符串入参，为了防止写错还会定义大量的字符串常量。
- 目前入参也是以Map和数组为主，导致入参过于随意，无法通过IDE限制入参，有些隐藏问题容易在运行阶段暴露出来。

我们是否应该考虑基于AOP的接口查询？当然在[sqltoy-quickstart](https://gitee.com/sagacity/sqltoy-quickstart#%E4%B8%BA%E4%BB%80%E4%B9%88dao%E4%B8%8D%E9%87%87%E7%94%A8mybatis-plus%E7%9A%84%E6%8E%A5%E5%8F%A3%E6%A8%A1%E5%BC%8F)也说明了一部分，但是我觉得AOP调用还是很有必要的。

目前个人认为有以下优势：
1. 非常友好且明确的查询定义，service中直接通过接口就能知道能有哪些查询，而不是去看sql.xml
```java
// 同时支持了返回泛型对象，sqlToyLazyDao则不支持
Map<String,Object> findById(Long id);
```
2. 和*.sql.xml可以有较强的关联性

**Comment by imyuyu** [comment]
目前dao查询：
```java
Map<String,Object> params = new HashMap<>():
// 此处无法限制入参的具体格式，不能从编码阶段就规避一些问题
params.put("id", "1234567")
sqlToyLazyDao.findBySql("findUserById", params, Map.class);
```

基于AOP接口查询
```java
// 这样调用，对开发来说更友好，而且兼容的大部分使用mybatis的开发人员
userInterface.findUserById(1234567L);
```

**Comment by chenrenfei** [comment]
理解你的想法，但sqltoy现在这种模式应该是从你这种理念演化来的
1、一开始大家都非常强调java 模式，严格遵循java core pattern理念。
2、随着技术框架的演化，发现dao层基本就是简单的转调，而无实质逻辑性代码，多了一个dao层就只为传一个sqlId

这个时候就是算账取舍了，合不合算的问题，就为了一个sqlId让项目中多出一堆dao
所以经过很多项目实践后，我们遵循一个原则：service必须按照接口和实现模式，但弱化机械性的空转dao层，用通用的dao来代替
