### ISSUE TITLE
返回类型为 Map 时，空字段如何返回

### ISSUE THREAD

**Issue by DFreeMind** [sagframe/sagacity-sqltoy#52]
sqltoy SQL的返回类型如果四 Map 类型，如果字段值为空时或自动忽略该字段，如果配置不忽略为空的字段

**Comment by chenrenfei** [comment]
将返回类型设置为LinkedHashMap
比如：findBySql(sql,valueMap,LinkedHashMap.class)

**Comment by DFreeMind** [comment]
非sqltoy问题，需要配置 jackson
