### ISSUE TITLE
增加一个数据库兼容性的测试模式

### ISSUE THREAD

**Issue by syin45** [sagframe/sagacity-sqltoy#56]
在产品开发阶段，一次测试就能够测试产品跨数据库的兼容性，避免一个一个测试不同数据库的麻烦。在该模式下，假设正常配置的是Oracle数据库，任何的增啥改查操作与正常模式没任何区别。但是，它同时又能生成MySQL数据库对应的查询语句并且同时投放到MySQL数据库上执行，这额外的操作当且仅当做数据库的兼容性测试，能够输出日志即可，其结果不影响原来的业务流程。

**Comment by chenrenfei** [comment]
是一个好的idea，后面可以尝试支持

**Comment by chenrenfei** [comment]
5.2.9.RC1 版本你可以体验一下了
1、项目中配置额外的数据库连接
2、额外设置redoDataSources 数组参数：

```
spring.sqltoy.redoDataSources[0]=oracle
spring.sqltoy.redoDataSources[1]=sqlserver
```
