### ISSUE TITLE
5.3 版本开始支持TDengine和influxDB 时序数据库

### ISSUE THREAD

**Issue by chenrenfei** [sagframe/sagacity-sqltoy#57]
1、计划逐步开始支持主流时序数据库TDengine、influxDB

**Comment by aiwthao** [comment]
个人认为 真的不是很好用 用起来很繁琐

**Comment by HaohanLove** [comment]
十分繁琐，文档不清楚，id自增数字主键都没有，自带的策略全是String类型的（可能是我还没找到 =_=）

**Comment by chenrenfei** [comment]
确实不好用，底层设计比较奇特，底层分无数张子表，在插入时还要针对子表名字插入，不是内部分区模式
