### ISSUE TITLE
建议增加数据更新时乐观锁支持

### ISSUE THREAD

**Issue by llm163520** [sagframe/sagacity-sqltoy#58]
场景：在更新数据之前用户已经获取到了完整的数据，修改之后完之后提交；在执行数据更新时避免数据覆盖
解决方案：在数据对象中增加version属性支持，数据执行更新时和数据库存量数据版本进行比较如果更新失败则抛数据异常已被XX更新，如果成功则值累加
示例：
实体标记属性
![image](https://user-images.githubusercontent.com/22343834/190308241-10f15218-41c2-45c4-b098-694c673998d4.png)
实际执行SQL：
update user set version=verison+1, remark='测试' where id='1' and version='0'

**Comment by chenrenfei** [comment]
5.2.11 版本支持

**Comment by chenrenfei** [comment]
5.2.11.RC1 目前已经支持
1、通过类上注解@DataVersion(field = "dataVersion")，字段上注解：@DataVersion
2、save操作时会自动初始化版本值
3、update操作时，首先锁记录校验版本是否发生变化，没有变化则进行更新，否则报错
```java
@Entity(tableName = "sqltoy_staff_info", pk_constraint = "PRIMARY")
@DataVersion(field = "dataVersion", startDate = true)
public class StaffInfoVO implements Serializable {
}
```
