### ISSUE TITLE
SqlToyLazyDao.findBySql 参数问题

### ISSUE THREAD

**Issue by lichangshu** [sagframe/sagacity-sqltoy#59]
方法 `SqlToyLazyDao.findBySql` 的参数为什么使用 T, 而不是 Class<T> ? 
如下:
```
public <T extends Serializable> List<T> SqlToyLazyDao.findBySql(final String sqlOrNamedSql, final T entity);
public <T extends Serializable> List<T> SqlToyLazyDao.findBySql(final String sqlOrNamedSql, final Class<T> entity);
```

**Comment by chenrenfei** [comment]
这个是实体对象传参数

**Comment by lichangshu** [comment]
建议再添加一个，这样不会与其他的框架出现语义的分歧，或者改个名字好理解

**Comment by chenrenfei** [comment]
用：public QueryResult findByQuery(final QueryExecutor query);来调用吧
因为现在有findBySql(String sql,Map queryMap,Class resultType) 如果再加一个findBySql(String sql,Serializable dto,Class resultType) 当调用findBySql(sql,null,resultClass) 时会有问题
