### ISSUE TITLE
EntityQuery.create().filters方法无效问题

### ISSUE THREAD

**Issue by yangandiris** [sagframe/sagacity-sqltoy#63]
版本：5.2.29.jre11
数据库：DM
使用方式：
<img width="793" alt="image" src="https://user-images.githubusercontent.com/6008810/210739215-2a6b07f8-1737-4429-814c-83987b0990b5.png">
执行sql：
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/6008810/210739610-806d4fc7-32a6-40f8-a00a-54a92c87a254.png">

**Comment by chenrenfei** [comment]
这里的filter不是增加条件，增加条件是EntityQuery.create().where("id=:id and username=:username"),filter是对应
xml中的filter（当参数值等于xx时，参数变成null）：
```xml
<sql id="show_case">
<filters>
   <!-- 参数statusAry只要包含-1(代表全部)则将statusAry设置为null不参与条件检索 -->
   <eq params="statusAry" value="-1" />
</filters>
<value><![CDATA[
	select 	*
	from sqltoy_device_order_info t 
	where #[t.status in (:statusAry)]
		  #[and t.ORDER_ID=:orderId]
		  #[and t.ORGAN_ID in (:authedOrganIds)]
		  #[and t.STAFF_ID in (:staffIds)]
		  #[and t.TRANS_DATE>=:beginAndEndDate[0]]
		  #[and t.TRANS_DATE<:beginAndEndDate[1]]    
	]]></value>
</sql>
```
