### ISSUE TITLE
VO生成问题

### ISSUE THREAD

**Issue by jkm6221** [sagframe/sagacity-sqltoy#64]
![image](https://user-images.githubusercontent.com/42882915/210961811-d42540af-fe29-49f3-ad6b-630208ae53b9.png)
![image](https://user-images.githubusercontent.com/42882915/210961914-0c923782-f792-4a96-8caa-3ad22c06ef4c.png)
如上图所示,  如果comment里面带有双引号, 则生成的VO里面引号内容不对

**Comment by chenrenfei** [comment]
https://gitee.com/sagacity/sagacity-quickvo/releases/tag/5.0.9
更新一下5.0.9 版本，感谢反馈

**Comment by jkm6221** [comment]
可是我用的是5.2.28版本这个今天下来的最新版诶

**Comment by jkm6221** [comment]
![image](https://user-images.githubusercontent.com/42882915/210974441-c4c4157d-f376-4659-82d6-ba55131eca82.png)

**Comment by chenrenfei** [comment]
quickvo工具版本
