### ISSUE TITLE
oracle方言问题

### ISSUE THREAD

**Issue by jkm6221** [sagframe/sagacity-sqltoy#65]
报错内容:  java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
生成的语法: select id,subject_name from base_course  offset 0 rows fetch next 20 rows only  
db配置和debug输出如下
![微信截图_20230109171112](https://user-images.githubusercontent.com/42882915/211273878-65071f85-3871-417e-a1ca-cac28a7edb6d.png)

**Comment by jkm6221** [comment]
fetch next 20 应该是sqlServer的写法吧, oracle是rownum那一套

**Comment by jkm6221** [comment]
要配oracle11g是吧?  有没有spring.sqltoy.dialect这个配置可选值的列表

**Comment by jkm6221** [comment]
org.sagacity.sqltoy.SqlToyContext#setDialect  这个设置方言的地方,没带上oracle11g

**Comment by chenrenfei** [comment]
不用设置dialect，sqltoy会自动识别

**Comment by jkm6221** [comment]
好 , 可以了
