### ISSUE TITLE
@loop 适用范围增强，支持in/not in参数

### ISSUE THREAD

**Issue by llm163520** [sagframe/sagacity-sqltoy#70]
预期SQL模板：
select * from table t where 1=1 AND @loop(:arg, (
( t.f1 = :arg[i].f1 AND t.f2=:arg[i].f2 and t.f3 in(arg[i].f3)),
' or '
)
预期结果：
select * from table t where 1=1 AND (
	( t.f1 = '1.1' AND t.f2='1.2' and t.f3 in('1.3','1.4'))
	or
	( t.f1 = '2.1' AND t.f2='2.2' and t.f3 in('2.3','2.4'))
)

**Comment by chenrenfei** [comment]
5.2.46.RC1 试一下

**Comment by llm163520** [comment]
测试用例：
String sql3 = """
                select * from table t where 1=1 AND (@loop(:arg, 
                         ( t.f1 = ':arg[i].f1' AND t.f2=:arg[i].f2 #[and t.f3 in(:arg[i].f3)] #[and t.f4 not in(:arg[i].f3)] ),
                         ' or '
                         )
                    )
            """;
        List<Map<String, Object>> list = Lists.newArrayList();
        list.add(ImmutableMap.of("f1", "1.1", "f2", "1.2", "f3", new Object[]{"1.3", "1.4"}));
        list.add(ImmutableMap.of("f1", "2.1", "f2", "2.2", "f3", Lists.newArrayList("2.3", "2.4", "2.5")));
        list.add(ImmutableMap.of("f1", "3.1", "f2", "3.2"));
        SqlToyResult sqlToyResult3 = SqlConfigParseUtils.processSql(sql3, MapKit.keys("arg").values(list));
        System.out.println(sqlToyResult3.getSql());
        System.out.println(JSON.toJSONString(sqlToyResult3.getParamsValue()));
测试结果：
select * from table t where 1=1 AND (     ( t.f1 = '1.1 ' AND t.f2='1.2' and t.f3 in('1.3','1.4' )    and t.f4 not in('1.3','1.4')  )  or   ( t.f1 = '2.1 ' AND t.f2='2.2' and t.f3 in('2.3','2.4','2.5' )    and t.f4 not in('2.3','2.4','2.5')  )  or   ( t.f1 = '3.1 ' AND t.f2='3.2') 
        )
结论：满足预期测试结果
