### ISSUE TITLE
分库分表能和shardingsphere配合使用吗，感觉一个项目牵扯的功能过多会导致多而不精这种情况😂，进而维护困难

### ISSUE THREAD

**Issue by clay-f** [sagframe/sagacity-sqltoy#76]
比如只专注与orm的某一部分功能，而不是大而全，这样导致维护进度慢，要改的东西太多，与别的开源项目整合这样不是更好嘛。

**Comment by chenrenfei** [comment]
shardingsphere是jdbc层面的分库分表，其实已经跟普通的orm无关了

**Comment by chenrenfei** [comment]
sqltoy的分库分表写于2016年并经历了拉卡拉数据平台几年的实践，这跟sqltoy的经历有关，从表分区到分表再到分库分表，再到引入elasticsearch，而现在基本上不提分库分表，因为目前我们已经大量使用mpp数据库，在分布式数据库自身解决了这些问题（所以分库分表对sqltoy而言就是一个非常普通的常规特性，从来都不去作为什么亮点介绍）
