### ISSUE TITLE
加载sql.xml日志输出能关闭吗，如果有200个文件，那启动日志岂不是要很长

### ISSUE THREAD

**Issue by clay-f** [sagframe/sagacity-sqltoy#77]
application.yml能配置日志输出嘛，优化格式输出。如果sql文件多，日志输出也会很多

    总计将加载.sql.xml文件数量为:2
    如果.sql.xml文件不在下列清单中,很可能是文件没有在编译路径下(bin、classes等),请仔细检查!
    正在解析第:[0]个sql文件:foo.sql.xml
    正在解析第:[1]个sql文件:foo1.sql.xml
    已经开启sql文件变更检测，会自动间隔:2秒检测一次,发生变更会自动重新载入!

**Comment by chenrenfei** [comment]
后面会调整一下，正在解析这个只有debug模式下才输出

**Comment by clay-f** [comment]
我现在用的版本是sagacity-sqltoy-starter 5.3.34

配置文件application.yml，一样有正在解析日志呀
@chenrenfei 

    spring:
      application:
        name: sqltoylearn
      main:
        banner-mode: off
      datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        username: scott
        password: 123456
        url: jdbc:oracle:thin:@//127.0.0.1:1521/xe
        hikari:
          minimum-idle: 5
          idle-timeout: 30000
          max-lifetime: 2000000
          maximum-pool-size: 20
          connection-timeout: 30000
          connection-test-query: select 1 from dual
      sqltoy:
        # 这里要注意，指定sql文件的目录(是目录不是具体文件或文件匹配表达式),多个可以用逗号分隔，会自动向下寻找
        sqlResourcesDir: classpath:/com/sqltoy/quickstart
        # 缓存翻译的配置
        translateConfig: classpath:sqltoy-translate.xml
        # debug模式会打印执行sql
        debug: false
        # 跨数据库函数自适配,比如:mysql的sql可以自动适用于oracle
        functionConverts: default
        # 提供统一字段:createBy createTime updateBy updateTime 等字段补漏性(为空时)赋值(可选配置)
        #unifyFieldsHandler: com.sqltoy.plugins.SqlToyUnifyFieldsHandler
        # sql执行超过多长时间则进行日志输出,用于监控哪些慢sql(可选配置:默认30秒)
        printSqlTimeoutMillis: 300000
  
![屏幕截图 2023-08-04 235823](https://github.com/sagframe/sagacity-sqltoy/assets/16079417/ec590e05-43f2-4657-9525-4579872f3557)

**Comment by chenrenfei** [comment]
5.3.35 已经发版，变成log.debug模式，如果log非debug就不输出
