### ISSUE TITLE
问一下能够与SLF4J集成吗，使用spring boot的时候经常会使用这个日志框架，将sql日志保存下来方便检查

### ISSUE THREAD

**Issue by clay-f** [sagframe/sagacity-sqltoy#84]
如果能够与SLF4J进行集成，能够使用logback、log4j2之类的日志库，然后使用log配置文件就很方便，日志轮询定时清理等等

**Comment by chenrenfei** [comment]
本身就是基于slf4j集成的呀，我们项目都是呀

**Comment by clay-f** [comment]
日志文档记录的不全😅，[快速上手使用配置](https://github.com/sagframe/sqltoy-online-doc/blob/master/docs/sqltoy/quickstart.md)只看到一个debug: true/false，没看到怎么进行关联，将日志与日志框架进行结合起来使用



例如hibernate这样配置，既可以使用日志框架，又能在控制台打印日志

    spring:
      jpa:
        properties:
          hibernate:
            format_sql: true
    logging:
      level:
        org:
          hibernate:
            SQL: DEBUG


logback， logback.xml能使用日志框架包名，进行日志配置输出

    <logger name="mapperPackageName" level="debug"/>

**Comment by chenrenfei** [comment]
所有的日志定义都是基于slf4j
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
	
/**
	 * 定义日志
	 */
	protected final Logger logger = LoggerFactory.getLogger(SqlToyContext.class);
