### ISSUE TITLE
问一下大佬，使用sqltoy如何将单项目改造成saas版本吗，有啥样例没

### ISSUE THREAD

**Issue by clay-f** [sagframe/sagacity-sqltoy#85]
例如mybatis，有两种（1）基于拦截器Interceptor，在表后面添加隔离字段（2）AbstractRoutingDataSource 基于分库的解决办法

然后我看了 sqltoy的[文档](https://github.com/sagframe/sqltoy-online-doc/)，网上查了解决样例也没有类似的功能，感觉sqltoy只适合那种单项目版的工具，应该是我菜，哈哈，所以想问一下大佬有没有啥类似的工具功能/解决办法，例如怎么自定义sqltoy实现saas版本项目😅😅

**Comment by chenrenfei** [comment]
sqltoy有多租户隔离策略，看文档，我们自身项目就是多租户SaaS平台

**Comment by chenrenfei** [comment]
多租户绝对不是多数据库，不是分库分表来解决多租户，分库分表一般解决性能问题

**Comment by clay-f** [comment]
找到了[样例代码](https://gitee.com/sagacity/sqltoy-showcase/tree/master/trunk/sqltoy-dynamic-datasource)感谢大佬回复，我晚上研究一下，应该是我对saas版系统架构理解有偏差了，传统的理解多租户有三种：column、schema、database

**Comment by clay-f** [comment]
😅多租户，[首页文档](https://github.com/sagframe/sagacity-sqltoy)介绍好少，多[数据源样例](https://gitee.com/sagacity/sqltoy-showcase/tree/master/trunk/sqltoy-dynamic-datasource)看了一下，使用的是 mybatis-plus插件[多数据源](https://baomidou.com/pages/a61e1b/)，好像与saas版本相差很远

google搜索了一圈，也没找到合适的样例，有没有那种介绍sqltoy具体怎么配置，比如在那个地方实现啥功能转向saas版本，转了一圈感觉就是要从头开始开发，然后都要自定义开发，所以想问一下有没有那种简单易懂的文档啊😂，研究了1天半还是没弄明白怎么入手从哪里开始修改

**Comment by clay-f** [comment]
找到saas column模式介绍了，在word文档有介绍，我有空在研究会儿，感谢大佬
